export type Lang = "vi" | "en";

const vi = {
  brand: "Dolphin CRM",
  nav: {
    overview: "Tổng quan",
    schedule: "Lịch",
    manage: "Quản lý",
    students: "Học viên",
    courses: "Khóa học",
    classes: "Lớp học",
    teachers: "Giáo viên",
    rooms: "Phòng",
    packages: "Subscription",
    enrollGroup: "Tuyển sinh",
    midEnroll: "Ghi danh giữa khóa",
    promotion: "Promotion",
    care: "Chăm sóc",
    finance: "Tài chính",
    collect: "Thu học phí",
    holds: "Bảo lưu",
    revenue: "Doanh thu",
    ops: "Vận hành",
    attend: "Điểm danh tay",
    attendQr: "Điểm danh QR",
    tasks: "Tác vụ",
    bookings: "Đặt phòng thuê",
    ai: "AI vận hành",
    feesShort: "Học phí",
    attendShort: "Điểm danh",
    enrollShort: "Đăng ký",
    support: "Support",
  },
  role: { owner: "Quản lý", reception: "Lễ tân", teacher: "Giáo viên" },
  status: {
    active: "Đang học",
    trial: "Học thử",
    paused: "Tạm nghỉ",
    present: "Có mặt",
    absent: "Vắng",
    excused: "Có phép",
    paid: "Đã thu",
    partial: "Thu một phần",
    overdue: "Quá hạn",
    unpaid: "Chưa thu",
    upcoming: "Sắp học",
    ongoing: "Đang học",
    completed: "Đã học",
    cancelled: "Hủy",
    holdPending: "Chờ duyệt",
    holdApproved: "Đang bảo lưu",
    holdRejected: "Từ chối",
    holdEnded: "Đã hết",
    leadNew: "Mới",
    leadContacted: "Đã liên hệ",
    leadWon: "Chốt",
    leadLost: "Thất bại",
  },
  common: {
    allBranches: "Tất cả",
    branch: "Chi nhánh",
    room: "Phòng",
    teacher: "Giáo viên",
    course: "Khóa",
    class: "Lớp",
    status: "Trạng thái",
    level: "Level",
    student: "Học viên",
    today: "Hôm nay",
    save: "Lưu",
    cancel: "Hủy",
    close: "Đóng",
    back: "Quay lại",
    next: "Tiếp tục",
    confirm: "Xác nhận",
    search: "Tìm",
    cash: "Tiền mặt",
    transfer: "Chuyển khoản",
    choose: "Chọn",
    menu: "Menu",
    language: "Ngôn ngữ",
    logout: "Đăng xuất",
    sample: "dữ liệu mẫu",
    hiddenTeacher: "Ẩn với giáo viên",
    noPhone: "Ẩn số điện thoại",
    loading: "Đang tải…",
    notFound: "Không thấy lớp.",
  },
  choose: {
    title: "Chọn lĩnh vực",
    lead: "Mỗi lĩnh vực một bộ dữ liệu riêng trên máy này. Chọn xong rồi nhập PIN.",
    dance: "Lớp nhảy, học thử, học viên, học phí",
    english: "Lớp tiếng Anh, học thử, học viên, học phí",
    music: "Lớp nhạc, học thử, học viên, học phí",
    swim: "Lớp bơi, học thử, học viên, học phí",
  },
  login: {
    title: "Đăng nhập",
    hint: "{name} · Đăng nhập",
    enter: "Đăng nhập",
    pin: "PIN",
    pinLabel: "PIN (4 số)",
    pinPlaceholder: "0000",
    demoHeading: "Tài khoản demo",
    badPin: "Mã PIN không đúng",
    fail: "Không đăng nhập được",
    switch: "Đổi lĩnh vực",
    downloadApp: "Download App",
    downloadGuideTitle: "Hướng dẫn tải app trên mobile",
    downloadGuideAlt: "Hướng dẫn 5 bước thêm Dolphin CRM vào màn hình chính",
  },
  header: { attend: "Điểm danh", enroll: "Đăng ký", report: "Báo cáo" },
  dash: {
    title: "Tổng quan",
    quickAttend: "Điểm danh nhanh",
    enrollStudent: "Đăng ký học viên",
    viewReport: "Xem báo cáo",
    days7: "7 ngày",
    days30: "30 ngày",
    thisMonth: "Tháng này",
    activeStudents: "Học viên đang học",
    vsLast: "{n} so với tháng trước",
    todaySessions: "Buổi học hôm nay",
    classStudents: "{classes} lớp · {students} học viên",
    revenueMonth: "Doanh thu tháng này",
    revenuePeriod: "Doanh thu kỳ này",
    revenueHint: "{arrow} {pct}% · kỳ trước {prev}",
    debtOpen: "Công nợ chưa thu",
    debtHint: "{n} học viên · {share}% số phải thu",
    attendRate: "Tỷ lệ điểm danh",
    attendHint: "{arrow} {n} điểm so với kỳ trước",
    endingCourses: "Khóa sắp kết thúc",
    endingHint: "Trong 7 ngày · cần gia hạn",
    revenueDays: "Doanh thu {n} ngày",
    dayUnit: "ngày",
    teacherNoRevenue: "Giáo viên không xem doanh thu.",
    receipts: "phiếu thu",
    funnel: "Phễu tuyển sinh",
    funnelNote: "Lead chưa gắn chi nhánh nên phễu là của cả studio.",
    leadNew: "Lead mới",
    enrolled: "Đã ghi danh",
    todayClasses: "Lớp học hôm nay",
    noClassToday: "Hôm nay không có buổi học.",
    viewSchedule: "Xem toàn bộ lịch",
    soon: "Sắp tới",
    live: "Đang diễn ra",
    attend: "Điểm danh",
    tasks: "Việc cần xử lý",
    noTasks: "Không có việc cần xử lý",
    viewAll: "Xem tất cả",
    urgentHold: "Bảo lưu chờ duyệt",
    urgentBackup: "Giáo viên nghỉ chưa có backup",
    urgentFull: "Lớp đã đầy",
    watchDebt: "Học viên nợ hơn 7 ngày",
    watchEnd: "Khóa kết thúc trong 3 ngày",
    infoLead: "Lead mới chưa liên hệ",
    topCourses: "Top 5 khóa đang chạy",
    noCourse: "Chưa có khóa trong chi nhánh này.",
    noActivity: "Chưa có hoạt động.",
    urgent: "Khẩn cấp",
    watch: "Cần chú ý",
    info: "Thông tin",
    total: "Tổng",
    average: "trung bình",
    perDay: "/ngày",
    stale: "{n} lead chưa xử lý hơn 3 ngày",
    nextStep: "{n}% sang bước sau",
    studentCount: "{n} học viên",
    recent: "Hoạt động gần đây",
    todayWord: "hôm nay",
    yesterday: "hôm qua",
    daysAgo: "{n} ngày trước",
    paidFrom: "Đã thu {amount} từ {name}",
    marked: "{name} vừa điểm danh lớp {className}",
    holdApproved: "Duyệt bảo lưu cho {name}",
    student: "học viên",
  },
  students: {
    title: "Học viên",
    debt: "Công nợ",
    hasDebt: "Có nợ",
    remain: "Buổi còn",
    lowRemain: "Sắp hết buổi",
    hold: "Bảo lưu",
    paused: "Nghỉ",
    parent: "Phụ huynh",
    sendZalo: "Gửi Zalo",
    status: "Trạng thái",
    badgeStudy: "Đang học",
    badgeHold: "Bảo lưu",
    badgeDebt: "Nợ",
    badgePaused: "Nghỉ",
    count: "{n} học viên",
    search: "Tên, số học viên, số phụ huynh",
    searchName: "Tìm tên",
    phone: "Điện thoại",
    selected: "{n} đã chọn",
    flag: "Đánh dấu",
    export: "Xuất Excel",
    selectAll: "Chọn tất cả",
    selectOne: "Chọn {name}",
    flagged: "Đã đánh dấu",
    empty: "Chưa có học viên khớp bộ lọc.",
    emptyCta: "+ Đăng ký học viên",
    view: "Xem",
    collectQuick: "Thu học phí",
    copied: "Đã copy số",
  },
  teachers: {
    title: "Giáo viên",
    count: "{n} giáo viên",
    add: "+ Thêm giáo viên",
    edit: "Sửa giáo viên",
    search: "Tên hoặc số điện thoại",
    empty: "Chưa có giáo viên khớp bộ lọc.",
    styles: "Bộ môn",
    levels: "Level dạy",
    skills: "Chuyên môn",
    classes: "Số lớp",
    perWeek: "Buổi / tuần",
    name: "Họ tên",
    note: "Ghi chú",
    pin: "PIN đăng nhập",
    pinPh: "4 số (tuỳ chọn)",
    needFields: "Điền đủ tên, SĐT và chi nhánh.",
    needSkills: "Chọn ít nhất một bộ môn và một level.",
    needPin: "PIN phải gồm đúng 4 chữ số.",
    viewSchedule: "Xem lịch",
    loading: "Đang tải hồ sơ…",
    weekSessions: "Buổi tuần này",
    noSessions: "Không có buổi trong tuần.",
    capacity: "Sức chứa {n}",
    weekLoad: "Buổi tuần này",
    monthLoad: "Buổi tháng này",
    overload: "Lịch tuần denser hơn 10 buổi — cân nhắc giảm tải.",
    classCount: "{n} lớp đang dạy",
    markAbsence: "Ghi nghỉ",
    absenceNotePh: "Lý do nghỉ / ca cần thay",
    absenceSaved: "Đã ghi nghỉ.",
    absences: "Ngày nghỉ",
    noAbsence: "Chưa có ngày nghỉ.",
    clearAbsence: "Xóa",
    needCover: "Buổi cần thay",
    noCover: "Không có buổi cần thay.",
    findBackup: "Tìm giáo viên thay",
    backupList: "Gợi ý thay ca",
    noBackup: "Không tìm thấy giáo viên cùng chuyên môn.",
    status: {
      active: "Đang dạy",
      paused: "Tạm nghỉ",
      left: "Nghỉ việc",
    },
    tabs: {
      info: "Thông tin",
      schedule: "Lịch dạy",
      workload: "Workload",
      backup: "Backup / Nghỉ",
    },
  },
  schedule: {
    title: "Lịch",
    week: "Tuần",
    month: "Tháng",
    create: "Tạo buổi lẻ",
    export: "Xuất lịch",
    sync: "Đồng bộ",
    prevWeek: "Tuần trước",
    nextWeek: "Tuần sau",
    prevMonth: "Tháng trước",
    nextMonth: "Tháng sau",
    byRoom: "Theo phòng",
    byTeacher: "Theo giáo viên",
    byBranch: "Theo chi nhánh",
    course: "Khóa",
    day: "Ngày",
    start: "Bắt đầu",
    end: "Kết thúc",
    save: "Lưu buổi",
    emptyClass: "Chưa có học viên trong lớp.",
    attend: "Điểm danh",
    changeTeacher: "Đổi giáo viên",
    changeRoom: "Đổi phòng",
    cancel: "Hủy buổi",
    log: "Nhật ký",
    noChanges: "Chưa có thay đổi.",
    today: "Hôm nay",
    session: "Buổi",
    roster: "Sĩ số",
    cancelReason: "Lý do hủy",
  },
  attend: {
    title: "Điểm danh tay",
    rule: "Có mặt, vắng và có phép đều trừ 1 buổi. Buổi hủy không trừ. Không học bù.",
    noSession: "không có buổi hôm nay",
    seats: "Chỗ trống",
    cancelled: "Buổi đã hủy. Ghi nhận không trừ buổi.",
    hidden: "{n} học viên đang bảo lưu, không có trong danh sách điểm danh. Chỗ trong lớp vẫn giữ.",
    noSessionNote: "Hôm nay lớp này không có buổi. Vẫn ghi nhận được nếu cần.",
    markAll: "Điểm danh tất cả Có mặt",
    undo: "Hoàn tác",
    remain: "buổi còn",
    onHold: "Đang bảo lưu",
    marked: "Đã điểm danh {done}/{total}",
    done: "Xong",
    summary: "Tóm tắt buổi",
    confirmNote: "Học viên đã điểm danh đã bị trừ 1 buổi. Xác nhận không trừ thêm.",
    cancelledNote: "Buổi đã hủy nên không trừ buổi.",
    search: "Tìm tên học viên",
  },
  enroll: {
    title: "Ghi danh giữa khóa",
    existing: "Học viên có sẵn",
    create: "Tạo mới nhanh",
    branch: "Chi nhánh",
    left: "Buổi còn lại của khóa, không tính buổi đã hủy",
    package: "Gói sẽ trừ vào",
    pickPackage: "Chọn gói",
    hiddenPrice: "Giá ẩn với giáo viên. Vẫn ghi được số buổi.",
    student: "Học viên",
    course: "Khóa",
    extra: "Buổi cộng thêm",
    pack: "Gói",
    due: "Phải thu",
    debtOk: "Có thể ghi danh khi còn nợ. Buổi đã cộng ngay khi xác nhận.",
    confirm: "Xác nhận ghi danh",
    ended: "Khóa đã hết buổi.",
    joinFrom: "Được vào từ buổi {n}.",
    noSession: "Khóa chưa có buổi để ghi danh.",
    beginStop: "Begin ngừng nhận từ buổi 4.",
    interOdd: "Inter chỉ nhận các buổi lẻ.",
    advanceOnly: "Advance chỉ nhận buổi 1 và buổi 5.",
  },
  hold: {
    title: "Bảo lưu",
    empty: "Không có phiếu trong tab này.",
    reason: "Lý do xin bảo lưu",
    window: "Thời gian đề xuất",
    rules: "Kiểm tra luật",
    freeze: "Buổi còn được đóng băng, không trừ khi điểm danh.",
    approve: "Duyệt",
    reject: "Từ chối",
    endEarly: "Kết thúc sớm bảo lưu",
    managerOnly: "Chỉ Quản lý duyệt hoặc kết thúc bảo lưu.",
  },
  care: {
    title: "Chăm sóc",
    flow: "Mới → Đã liên hệ → Học thử → Chốt → Thất bại",
    kanban: "Kanban",
    table: "Bảng",
    add: "+ Thêm lead",
    source: "Nguồn",
    owner: "Người phụ trách",
    assignTo: "Gán cho",
    assign: "Gán hàng loạt",
    zalo: "Gửi Zalo mẫu",
    cold: "Lạnh hơn 3 ngày",
    addTitle: "Thêm lead",
    convert: "Chuyển thành học viên",
    converted: "Đã tạo học viên.",
    next: "Việc tiếp theo",
    saveReminder: "Lưu nhắc",
    addTouch: "Thêm hoạt động",
    call: "Gọi",
    note: "Ghi chú",
    write: "Ghi",
    timeline: "Dòng thời gian",
    coldLong: "Không có hoạt động hơn 3 ngày",
    interest: "Khóa quan tâm",
    nextPlaceholder: "Gọi lại, nhắn Zalo...",
    reminderDay: "Ngày nhắc",
    zaloText: "Chào bạn, {studio} nhận được thông tin quan tâm lớp. Mình gọi lại để xếp lịch học thử nhé.",
  },
  money: {
    title: "Thu học phí",
    teacher: "Giáo viên không xem học phí.",
    lead: "Tìm học viên, thu một phần hoặc đủ. Nợ cập nhật ngay.",
    method: "Hình thức",
    search: "Tìm học viên theo tên hoặc số",
    debt: "Còn nợ",
    item: "Khoản / gói cần thu",
    collect: "Thu tiền",
    typeName: "Gõ tên để mở sổ của học viên.",
    history: "Lịch sử thu",
    empty: "Chưa có phiếu trong bộ lọc.",
    collected: "Đã thu",
    print: "In phiếu",
    receipt: "Phiếu thu",
    revenue: "Doanh thu",
    revenueLead: "Đã thu và còn nợ theo chi nhánh. Số mẫu của studio, không phải báo cáo kế toán.",
    thisMonth: "Tháng này",
    collectedMonth: "Đã thu tháng này",
    day: "Ngày",
    amount: "Số tiền",
    note: "Ghi chú",
  },
  pages: {
    courses: "Khóa học",
    classes: "Lớp học",
    teachers: "Giáo viên",
    rooms: "Phòng",
    packages: "Subscription",
    createPackage: "Tạo plan mẫu",
    addSessions: "Mua / gia hạn subscription",
    addSessionsLead: "Tạo subscription gắn Course: còn hạn (start→end) và còn buổi thì học tiếp được.",
    enroll: "Tạo subscription",
    subPlans: "Plan mẫu",
    subActive: "Subscription đang có",
    subInvalid: "Subscription hết hạn hoặc hết buổi — cần renew.",
    subEnd: "Hết hạn",
    subLeft: "Buổi còn",
    renew: "Cần renew",
    packageName: "Tên gói",
    fee: "Học phí",
    savePackage: "Lưu gói",
    promotion: "Promotion",
    promotionLead: "Chương trình mẫu của studio. Giá sản phẩm Dolphin CRM vẫn là TODO.",
    tasks: "Tác vụ",
    booking: "Đặt phòng thuê",
    bookingLead: "Phí thuê phòng là số mẫu của studio, không phải giá sản phẩm Dolphin.",
    ai: "AI vận hành",
    aiLead: "Chưa nối mô hình. Gợi ý dưới đây chỉ đọc dữ liệu mẫu trên máy.",
    overdueTasks: "Tác vụ quá hạn",
    noOverdue: "Không có tác vụ quá hạn.",
    debtors: "Học viên còn nợ",
    qr: "Điểm danh QR",
    qrLead: "Mã giả lập trên máy, không phải QR ngân hàng hay cổng điểm danh thật.",
    fakeScan: "Giả lập quét",
    pickStudent: "Chọn học viên trong lớp",
    scanned: "{name} đã được ghi có mặt.",
    open: "Đang mở",
    pausedCourse: "Tạm dừng",
    classCount: "{n} lớp",
    people: "{n} người",
    roomUse: "{n} lớp dùng phòng này",
    running: "Đang chạy",
    endedPromo: "Hết hạn",
    overdue: "quá hạn",
    reopen: "Mở lại",
    done: "Xong",
    booked: "Đã đặt",
    bookingDone: "Đã xong",
    sessions: "buổi",
    pack: "Gói",
    sessionCount: "Số buổi",
    fromDay: "Từ ngày",
    toDay: "Đến ngày",
    amount: "Số tiền",
    bill: "Ảnh bill",
    billTooBig: "Ảnh bill lớn hơn 1,5 MB.",
    noPackage: "Chưa có gói",
    noCourse: "Chưa có khóa",
    remain: "còn",
    pickItem: "Chọn khoản cần thu.",
  },
  catalog: {
    createCourse: "Tạo khóa",
    preview: "Xem",
    edit: "Sửa",
    style: "Phong cách",
    description: "Mô tả",
    weekdays: "Thứ học",
    capacity: "Sĩ số",
    capacityMax: "Số học viên tối đa",
    capacityCurrent: "Số học viên hiện tại",
    studentsFill: "{n}/{cap}",
    floor: "Tầng",
    phone: "Số điện thoại",
    addTeacher: "Thêm giáo viên",
    addRoom: "Thêm phòng",
    viewOnly: "Giáo viên chỉ xem.",
    needFields: "Điền đủ tên, giáo viên và phòng.",
    needWeekday: "Chọn ít nhất một thứ.",
    roomBranch: "Phòng không thuộc chi nhánh này.",
    pause: "Tạm dừng",
    reopen: "Mở lại",
  },
  task: {
    title: "Tác vụ",
    subtitle: "Việc nội bộ cho nhân sự studio.",
    list: "List",
    board: "Board",
    create: "Tạo việc",
    edit: "Sửa việc",
    empty: "Chưa có việc phù hợp bộ lọc.",
    titleField: "Tiêu đề",
    assignee: "Người nhận",
    unassigned: "Chưa gán",
    due: "Hạn",
    priority: "Ưu tiên",
    note: "Ghi chú",
    status: "Trạng thái",
    todo: "Todo",
    inprogress: "In progress",
    verify: "Verify",
    feedback: "Feedback",
    done: "Done",
    low: "Thấp",
    medium: "Trung bình",
    high: "Cao",
    overdueOnly: "Chỉ quá hạn",
    mine: "Của tôi",
    allStaff: "Mọi người",
    needTitle: "Nhập tiêu đề việc.",
    viewOnly: "Giáo viên chỉ xem và kéo việc của mình.",
    comments: "Lịch sử comment",
    commentPlaceholder: "Viết comment…",
    sendComment: "Gửi",
    noComments: "Chưa có comment.",
    call: "Gọi",
    zalo: "Zalo",
    needComment: "Nhập nội dung comment.",
    parent: "Nhóm việc",
    allParents: "Mọi nhóm",
    noParent: "Không nhóm",
    createParent: "Tạo nhóm",
    parentName: "Tên nhóm",
    needParentName: "Nhập tên nhóm.",
  },
  week: {
    sun: "Chủ nhật",
    mon: "Thứ 2",
    tue: "Thứ 3",
    wed: "Thứ 4",
    thu: "Thứ 5",
    fri: "Thứ 6",
    sat: "Thứ 7",
    sunShort: "CN",
    monShort: "T2",
    tueShort: "T3",
    wedShort: "T4",
    thuShort: "T5",
    friShort: "T6",
    satShort: "T7",
  },
  drawer: {
    info: "Thông tin",
    courses: "Khóa đang học",
    attendance: "Điểm danh",
    money: "Thanh toán",
    hold: "Bảo lưu",
    activity: "Hoạt động",
    enrollMore: "Ghi danh thêm",
    collect: "Thu học phí",
    marked: "Điểm danh {className} · {status}",
    holdLine: "Bảo lưu {status} · {reason}",
    notDeducted: "không trừ",
    close: "Đóng",
    fullName: "Họ tên",
    email: "Email",
    birthDay: "Ngày sinh",
    branch: "Chi nhánh",
    parent: "Phụ huynh",
    parentRequired: "Bắt buộc nếu dưới 18 tuổi",
    notes: "Ghi chú nội bộ",
    notesEmpty: "Chưa có ghi chú.",
    notePlaceholder: "Thêm ghi chú nội bộ",
    joined: "Ngày tạo",
    creator: "Người tạo",
    noCourse: "Chưa gắn khóa",
    sessionsLeft: "còn {n} buổi",
    changeClass: "Đổi lớp",
    pickClass: "Chọn lớp mới",
    attendRate: "Tỷ lệ có mặt",
    ofSessions: "{present}/{total} buổi",
    filterCourse: "Lọc khóa / lớp",
    allCourses: "Mọi lớp",
    day: "Ngày",
    classCol: "Lớp",
    statusCol: "Trạng thái",
    noAttend: "Chưa có điểm danh.",
    paidTotal: "Đã thu",
    outstanding: "Công nợ",
    method: "Hình thức",
    amount: "Số tiền",
    note: "Ghi chú",
    noPayments: "Chưa có phiếu thu.",
    noHold: "Không đang bảo lưu.",
    holdHistory: "Lịch sử",
    noHoldHistory: "Chưa có phiếu bảo lưu.",
    requestHold: "Xin bảo lưu",
    holdReason: "Lý do bảo lưu",
    holdFrom: "Từ ngày",
    holdTo: "Đến ngày",
    holdSent: "Đã gửi phiếu chờ duyệt.",
    holdError: "Không gửi được phiếu bảo lưu.",
    noActivity: "Chưa có hoạt động.",
    phoneHidden: "Giáo viên không xem số điện thoại",
    loading: "Đang tải hồ sơ…",
    package: "Gói",
    capacity: "Sĩ số {n}/{cap}",
    approver: "Duyệt bởi",
  },
};

const en: typeof vi = {
  brand: "Dolphin CRM",
  nav: {
    overview: "Overview",
    schedule: "Schedule",
    manage: "Manage",
    students: "Students",
    courses: "Courses",
    classes: "Classes",
    teachers: "Teachers",
    rooms: "Rooms",
    packages: "Subscriptions",
    enrollGroup: "Enrollment",
    midEnroll: "Mid-course enroll",
    promotion: "Promotion",
    care: "Follow-up",
    finance: "Finance",
    collect: "Collect fees",
    holds: "Holds",
    revenue: "Revenue",
    ops: "Operations",
    attend: "Attendance",
    attendQr: "QR attendance",
    tasks: "Tasks",
    bookings: "Room bookings",
    ai: "Ops assistant",
    feesShort: "Fees",
    attendShort: "Attendance",
    enrollShort: "Enroll",
    support: "Support",
  },
  role: { owner: "Manager", reception: "Front desk", teacher: "Teacher" },
  status: {
    active: "Active",
    trial: "Trial",
    paused: "Paused",
    present: "Present",
    absent: "Absent",
    excused: "Excused",
    paid: "Paid",
    partial: "Partial",
    overdue: "Overdue",
    unpaid: "Unpaid",
    upcoming: "Upcoming",
    ongoing: "In class",
    completed: "Done",
    cancelled: "Cancelled",
    holdPending: "Pending",
    holdApproved: "On hold",
    holdRejected: "Rejected",
    holdEnded: "Ended",
    leadNew: "New",
    leadContacted: "Contacted",
    leadWon: "Won",
    leadLost: "Lost",
  },
  common: {
    allBranches: "All",
    branch: "Branch",
    room: "Room",
    teacher: "Teacher",
    course: "Course",
    class: "Class",
    status: "Status",
    level: "Level",
    student: "Student",
    today: "Today",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    next: "Continue",
    confirm: "Confirm",
    search: "Search",
    cash: "Cash",
    transfer: "Transfer",
    choose: "Choose",
    menu: "Menu",
    language: "Language",
    logout: "Log out",
    sample: "sample data",
    hiddenTeacher: "Hidden from teachers",
    noPhone: "Phone hidden",
    loading: "Loading…",
    notFound: "Class not found.",
  },
  choose: {
    title: "Choose a field",
    lead: "Each field keeps its own data on this device. Then enter a PIN.",
    dance: "Dance classes, trials, students, fees",
    english: "English classes, trials, students, fees",
    music: "Music classes, trials, students, fees",
    swim: "Swim classes, trials, students, fees",
  },
  login: {
    title: "Sign in",
    hint: "{name} · Sign in",
    enter: "Sign in",
    pin: "PIN",
    pinLabel: "PIN (4 digits)",
    pinPlaceholder: "0000",
    demoHeading: "Demo accounts",
    badPin: "Wrong PIN",
    fail: "Could not sign in",
    switch: "Change field",
    downloadApp: "Download App",
    downloadGuideTitle: "How to install the app on mobile",
    downloadGuideAlt: "5-step guide to add Dolphin CRM to the home screen",
  },
  header: { attend: "Attendance", enroll: "Enroll", report: "Report" },
  dash: {
    title: "Overview",
    quickAttend: "Quick attendance",
    enrollStudent: "Enroll student",
    viewReport: "View report",
    days7: "7 days",
    days30: "30 days",
    thisMonth: "This month",
    activeStudents: "Active students",
    vsLast: "{n} vs last month",
    todaySessions: "Sessions today",
    classStudents: "{classes} classes · {students} students",
    revenueMonth: "Revenue this month",
    revenuePeriod: "Revenue this period",
    revenueHint: "{arrow} {pct}% · previous {prev}",
    debtOpen: "Open balance",
    debtHint: "{n} students · {share}% of billed",
    attendRate: "Attendance rate",
    attendHint: "{arrow} {n} points vs previous period",
    endingCourses: "Courses ending soon",
    endingHint: "Within 7 days · needs renewal",
    revenueDays: "Revenue {n} days",
    dayUnit: "days",
    teacherNoRevenue: "Teachers cannot see revenue.",
    receipts: "receipts",
    funnel: "Enrollment funnel",
    funnelNote: "Leads are not tied to a branch, so the funnel is studio-wide.",
    leadNew: "New leads",
    enrolled: "Enrolled",
    todayClasses: "Classes today",
    noClassToday: "No session today.",
    viewSchedule: "View full schedule",
    soon: "Upcoming",
    live: "In progress",
    attend: "Attendance",
    tasks: "Needs attention",
    noTasks: "Nothing to handle",
    viewAll: "View all",
    urgentHold: "Holds waiting for approval",
    urgentBackup: "Teacher off with no backup",
    urgentFull: "Class is full",
    watchDebt: "Students in debt over 7 days",
    watchEnd: "Courses ending within 3 days",
    infoLead: "New leads not contacted",
    topCourses: "Top 5 running courses",
    noCourse: "No course in this branch.",
    noActivity: "No activity yet.",
    urgent: "Urgent",
    watch: "Watch",
    info: "Info",
    total: "Total",
    average: "average",
    perDay: "/day",
    stale: "{n} leads untouched for 3 days",
    nextStep: "{n}% to the next step",
    studentCount: "{n} students",
    recent: "Recent activity",
    todayWord: "today",
    yesterday: "yesterday",
    daysAgo: "{n} days ago",
    paidFrom: "Collected {amount} from {name}",
    marked: "{name} was marked in {className}",
    holdApproved: "Hold approved for {name}",
    student: "student",
  },
  students: {
    title: "Students",
    debt: "Balance",
    hasDebt: "Has balance",
    remain: "Sessions left",
    lowRemain: "Running low",
    hold: "On hold",
    paused: "Paused",
    parent: "Parent",
    sendZalo: "Send Zalo",
    status: "Status",
    badgeStudy: "Active",
    badgeHold: "On hold",
    badgeDebt: "Balance",
    badgePaused: "Paused",
    count: "{n} students",
    search: "Name, student number, parent number",
    searchName: "Search name",
    phone: "Phone",
    selected: "{n} selected",
    flag: "Flag",
    export: "Export Excel",
    selectAll: "Select all",
    selectOne: "Select {name}",
    flagged: "Flagged",
    empty: "No students match these filters.",
    emptyCta: "+ Enroll student",
    view: "View",
    collectQuick: "Collect fee",
    copied: "Phone copied",
  },
  teachers: {
    title: "Teachers",
    count: "{n} teachers",
    add: "+ Add teacher",
    edit: "Edit teacher",
    search: "Name or phone",
    empty: "No teachers match these filters.",
    styles: "Subjects",
    levels: "Levels taught",
    skills: "Skills",
    classes: "Classes",
    perWeek: "Sessions / week",
    name: "Full name",
    note: "Note",
    pin: "Login PIN",
    pinPh: "4 digits (optional)",
    needFields: "Enter name, phone, and branch.",
    needSkills: "Pick at least one subject and one level.",
    needPin: "PIN must be exactly 4 digits.",
    viewSchedule: "View schedule",
    loading: "Loading profile…",
    weekSessions: "Sessions this week",
    noSessions: "No sessions this week.",
    capacity: "Capacity {n}",
    weekLoad: "This week",
    monthLoad: "This month",
    overload: "More than 10 sessions this week — consider reducing load.",
    classCount: "{n} classes teaching",
    markAbsence: "Mark absence",
    absenceNotePh: "Reason / cover needed",
    absenceSaved: "Absence saved.",
    absences: "Absence days",
    noAbsence: "No absences yet.",
    clearAbsence: "Remove",
    needCover: "Sessions needing cover",
    noCover: "No sessions need cover.",
    findBackup: "Find backup teacher",
    backupList: "Cover suggestions",
    noBackup: "No teachers with matching skills.",
    status: {
      active: "Teaching",
      paused: "On leave",
      left: "Left",
    },
    tabs: {
      info: "Info",
      schedule: "Schedule",
      workload: "Workload",
      backup: "Backup / Leave",
    },
  },
  schedule: {
    title: "Schedule",
    week: "Week",
    month: "Month",
    create: "Add session",
    export: "Export",
    sync: "Sync",
    prevWeek: "Previous week",
    nextWeek: "Next week",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    byRoom: "By room",
    byTeacher: "By teacher",
    byBranch: "By branch",
    course: "Course",
    day: "Date",
    start: "Start",
    end: "End",
    save: "Save session",
    emptyClass: "No students in this class.",
    attend: "Attendance",
    changeTeacher: "Change teacher",
    changeRoom: "Change room",
    cancel: "Cancel session",
    log: "Log",
    noChanges: "No changes yet.",
    today: "Today",
    session: "Session",
    roster: "Roster",
    cancelReason: "Cancel reason",
  },
  attend: {
    title: "Manual attendance",
    rule: "Present, absent, and excused each use 1 session. A cancelled session does not. No makeup class.",
    noSession: "no session today",
    seats: "Seats left",
    cancelled: "Session cancelled. Marks do not deduct a session.",
    hidden: "{n} students are on hold and are not in this list. Their seat stays.",
    noSessionNote: "This class has no session today. You can still mark if needed.",
    markAll: "Mark all present",
    undo: "Undo",
    remain: "left",
    onHold: "On hold",
    marked: "Marked {done}/{total}",
    done: "Done",
    summary: "Session summary",
    confirmNote: "Marked students already lost 1 session. Confirming does not deduct again.",
    cancelledNote: "This session was cancelled, so nothing is deducted.",
    search: "Search student name",
  },
  enroll: {
    title: "Mid-course enrollment",
    existing: "Existing student",
    create: "Quick create",
    branch: "Branch",
    left: "Sessions left in the course, cancelled ones excluded",
    package: "Package to charge",
    pickPackage: "Choose a package",
    hiddenPrice: "Price is hidden from teachers. Session count can still be saved.",
    student: "Student",
    course: "Course",
    extra: "Sessions to add",
    pack: "Package",
    due: "Amount due",
    debtOk: "You can enroll with an open balance. Sessions are added on confirm.",
    confirm: "Confirm enrollment",
    ended: "This course has no sessions left.",
    joinFrom: "Can join from session {n}.",
    noSession: "This course has no session to join.",
    beginStop: "Begin stops taking students from session 4.",
    interOdd: "Inter only joins odd-numbered sessions.",
    advanceOnly: "Advance only joins sessions 1 and 5.",
  },
  hold: {
    title: "Holds",
    empty: "Nothing in this tab.",
    reason: "Reason for the hold",
    window: "Requested dates",
    rules: "Rule check",
    freeze: "Remaining sessions stay frozen and are not deducted by attendance.",
    approve: "Approve",
    reject: "Reject",
    endEarly: "End hold early",
    managerOnly: "Only a manager can approve or end a hold.",
  },
  care: {
    title: "Follow-up",
    flow: "New → Contacted → Trial → Won → Lost",
    kanban: "Kanban",
    table: "Table",
    add: "+ Add lead",
    source: "Source",
    owner: "Owner",
    assignTo: "Assign to",
    assign: "Assign selected",
    zalo: "Send sample Zalo",
    cold: "Cold for 3 days",
    addTitle: "Add lead",
    convert: "Convert to student",
    converted: "Student created.",
    next: "Next step",
    saveReminder: "Save reminder",
    addTouch: "Add activity",
    call: "Call",
    note: "Note",
    write: "Save",
    timeline: "Timeline",
    coldLong: "No activity for more than 3 days",
    interest: "Course of interest",
    nextPlaceholder: "Call back, send Zalo...",
    reminderDay: "Reminder date",
    zaloText: "Hi, {studio} got your interest in a class. We will call to set a trial.",
  },
  money: {
    title: "Collect fees",
    teacher: "Teachers cannot see fees.",
    lead: "Find a student, then collect part or all. The balance updates immediately.",
    method: "Method",
    search: "Search by name or number",
    debt: "Balance",
    item: "Item to collect",
    collect: "Collect",
    typeName: "Type a name to open the student ledger.",
    history: "Collection history",
    empty: "No receipt in this filter.",
    collected: "Collected",
    print: "Print receipt",
    receipt: "Receipt",
    revenue: "Revenue",
    revenueLead: "Collected and still owed by branch. Studio sample figures, not an accounting report.",
    thisMonth: "This month",
    collectedMonth: "Collected this month",
    day: "Date",
    amount: "Amount",
    note: "Note",
  },
  pages: {
    courses: "Courses",
    classes: "Classes",
    teachers: "Teachers",
    rooms: "Rooms",
    packages: "Subscriptions",
    createPackage: "Create a plan template",
    addSessions: "Buy / renew subscription",
    addSessionsLead: "Create a course subscription: valid while start→end and sessions remain.",
    enroll: "Create subscription",
    subPlans: "Plan templates",
    subActive: "Active subscriptions",
    subInvalid: "Subscription expired or out of sessions — renew required.",
    subEnd: "Ends",
    subLeft: "Sessions left",
    renew: "Needs renew",
    packageName: "Package name",
    fee: "Fee",
    savePackage: "Save package",
    promotion: "Promotion",
    promotionLead: "Sample studio offers. Dolphin CRM product price is still TODO.",
    tasks: "Tasks",
    booking: "Room bookings",
    bookingLead: "Room rental fees are studio sample numbers, not a Dolphin product price.",
    ai: "Ops assistant",
    aiLead: "No model connected. The notes below only read the sample data on this device.",
    overdueTasks: "Overdue tasks",
    noOverdue: "No overdue tasks.",
    debtors: "Students with a balance",
    qr: "QR attendance",
    qrLead: "A fake code on this device, not a bank QR or a real attendance gate.",
    fakeScan: "Simulate a scan",
    pickStudent: "Choose a student in the class",
    scanned: "{name} marked present.",
    open: "Open",
    pausedCourse: "Paused",
    classCount: "{n} classes",
    people: "{n} people",
    roomUse: "{n} classes use this room",
    running: "Running",
    endedPromo: "Ended",
    overdue: "overdue",
    reopen: "Reopen",
    done: "Done",
    booked: "Booked",
    bookingDone: "Done",
    sessions: "sessions",
    pack: "Package",
    sessionCount: "Sessions",
    fromDay: "From",
    toDay: "To",
    amount: "Amount",
    bill: "Transfer slip",
    billTooBig: "The slip is larger than 1.5 MB.",
    noPackage: "No package yet",
    noCourse: "No course yet",
    remain: "left",
    pickItem: "Choose an item to collect.",
  },
  catalog: {
    createCourse: "Create a course",
    preview: "Preview",
    edit: "Edit",
    style: "Style",
    description: "Description",
    weekdays: "Weekdays",
    capacity: "Capacity",
    capacityMax: "Max students",
    capacityCurrent: "Current students",
    studentsFill: "{n}/{cap}",
    floor: "Floor",
    phone: "Phone",
    addTeacher: "Add a teacher",
    addRoom: "Add a room",
    viewOnly: "Teachers can only view this.",
    needFields: "Enter a name, a teacher, and a room.",
    needWeekday: "Pick at least one weekday.",
    roomBranch: "That room is not in this branch.",
    pause: "Pause",
    reopen: "Reopen",
  },
  task: {
    title: "Tasks",
    subtitle: "Internal work for studio staff.",
    list: "List",
    board: "Board",
    create: "New task",
    edit: "Edit task",
    empty: "No tasks match these filters.",
    titleField: "Title",
    assignee: "Assignee",
    unassigned: "Unassigned",
    due: "Due",
    priority: "Priority",
    note: "Note",
    status: "Status",
    todo: "Todo",
    inprogress: "In progress",
    verify: "Verify",
    feedback: "Feedback",
    done: "Done",
    low: "Low",
    medium: "Medium",
    high: "High",
    overdueOnly: "Overdue only",
    mine: "Mine",
    allStaff: "Everyone",
    needTitle: "Enter a task title.",
    viewOnly: "Teachers can view and move their own tasks.",
    comments: "Comment history",
    commentPlaceholder: "Write a comment…",
    sendComment: "Send",
    noComments: "No comments yet.",
    call: "Call",
    zalo: "Zalo",
    needComment: "Enter a comment.",
    parent: "Parent group",
    allParents: "All groups",
    noParent: "No group",
    createParent: "New group",
    parentName: "Group name",
    needParentName: "Enter a group name.",
  },
  week: {
    sun: "Sunday",
    mon: "Monday",
    tue: "Tuesday",
    wed: "Wednesday",
    thu: "Thursday",
    fri: "Friday",
    sat: "Saturday",
    sunShort: "Sun",
    monShort: "Mon",
    tueShort: "Tue",
    wedShort: "Wed",
    thuShort: "Thu",
    friShort: "Fri",
    satShort: "Sat",
  },
  drawer: {
    info: "Profile",
    courses: "Courses",
    attendance: "Attendance",
    money: "Payments",
    hold: "Holds",
    activity: "Activity",
    enrollMore: "Enroll again",
    collect: "Collect fee",
    marked: "Attendance {className} · {status}",
    holdLine: "Hold {status} · {reason}",
    notDeducted: "not deducted",
    close: "Close",
    fullName: "Full name",
    email: "Email",
    birthDay: "Birthday",
    branch: "Branch",
    parent: "Parent",
    parentRequired: "Required if under 18",
    notes: "Internal notes",
    notesEmpty: "No notes yet.",
    notePlaceholder: "Add an internal note",
    joined: "Created",
    creator: "Created by",
    noCourse: "No course linked",
    sessionsLeft: "{n} sessions left",
    changeClass: "Change class",
    pickClass: "Pick a new class",
    attendRate: "Attendance rate",
    ofSessions: "{present}/{total} sessions",
    filterCourse: "Filter by class",
    allCourses: "All classes",
    day: "Date",
    classCol: "Class",
    statusCol: "Status",
    noAttend: "No attendance yet.",
    paidTotal: "Collected",
    outstanding: "Balance due",
    method: "Method",
    amount: "Amount",
    note: "Note",
    noPayments: "No payments yet.",
    noHold: "Not on hold.",
    holdHistory: "History",
    noHoldHistory: "No hold records.",
    requestHold: "Request hold",
    holdReason: "Hold reason",
    holdFrom: "From",
    holdTo: "To",
    holdSent: "Hold request submitted.",
    holdError: "Could not submit hold.",
    noActivity: "No activity yet.",
    phoneHidden: "Teachers cannot see phone numbers",
    loading: "Loading profile…",
    package: "Package",
    capacity: "Roster {n}/{cap}",
    approver: "Approved by",
  },
};

export const copy = { vi, en };

export type Copy = typeof vi;

export function fill(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
}
